[2023-05-04T02:15:48.560+0000] {processor.py:153} INFO - Started process (PID=743) to work on /opt/airflow/dags/clone_repo.py
[2023-05-04T02:15:48.561+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/clone_repo.py for tasks to queue
[2023-05-04T02:15:48.562+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:15:48.562+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:15:48.566+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:15:48.565+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/clone_repo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/clone_repo.py", line 2, in <module>
    from airflow.providers.github.operators.github import GithubOperator
ModuleNotFoundError: No module named 'airflow.providers.github'
[2023-05-04T02:15:48.566+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:15:48.594+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/clone_repo.py took 0.040 seconds
[2023-05-04T02:15:55.634+0000] {processor.py:153} INFO - Started process (PID=744) to work on /opt/airflow/dags/clone_repo.py
[2023-05-04T02:15:55.636+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/clone_repo.py for tasks to queue
[2023-05-04T02:15:55.637+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:15:55.637+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:15:55.643+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:15:55.641+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/clone_repo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/clone_repo.py", line 2, in <module>
    from airflow.providers.github.operators.github import GithubOperator
ModuleNotFoundError: No module named 'airflow.providers.github'
[2023-05-04T02:15:55.643+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:15:55.676+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/clone_repo.py took 0.046 seconds
[2023-05-04T02:16:06.389+0000] {processor.py:153} INFO - Started process (PID=749) to work on /opt/airflow/dags/clone_repo.py
[2023-05-04T02:16:06.391+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/clone_repo.py for tasks to queue
[2023-05-04T02:16:06.392+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:16:06.392+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:16:06.398+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:16:06.397+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/clone_repo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/clone_repo.py", line 2, in <module>
    from airflow.providers.github.operators.github import GithubOperator
ModuleNotFoundError: No module named 'airflow.providers.github'
[2023-05-04T02:16:06.399+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:16:06.424+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/clone_repo.py took 0.047 seconds
[2023-05-04T02:16:31.259+0000] {processor.py:153} INFO - Started process (PID=763) to work on /opt/airflow/dags/clone_repo.py
[2023-05-04T02:16:31.260+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/clone_repo.py for tasks to queue
[2023-05-04T02:16:31.261+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:16:31.261+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:16:31.264+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:16:31.263+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/clone_repo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/clone_repo.py", line 18
    destination_
    ^
SyntaxError: positional argument follows keyword argument
[2023-05-04T02:16:31.265+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:16:31.298+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/clone_repo.py took 0.043 seconds
[2023-05-04T02:16:33.301+0000] {processor.py:153} INFO - Started process (PID=764) to work on /opt/airflow/dags/clone_repo.py
[2023-05-04T02:16:33.302+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/clone_repo.py for tasks to queue
[2023-05-04T02:16:33.303+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:16:33.302+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:16:33.306+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:16:33.304+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/clone_repo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/clone_repo.py", line 18
    destination_path
    ^
SyntaxError: positional argument follows keyword argument
[2023-05-04T02:16:33.306+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:16:33.331+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/clone_repo.py took 0.036 seconds
[2023-05-04T02:16:41.476+0000] {processor.py:153} INFO - Started process (PID=775) to work on /opt/airflow/dags/clone_repo.py
[2023-05-04T02:16:41.479+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/clone_repo.py for tasks to queue
[2023-05-04T02:16:41.483+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:16:41.482+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:16:41.496+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:16:41.493+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/clone_repo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/clone_repo.py", line 2, in <module>
    from airflow.providers.github.operators.github import GithubOperator
ModuleNotFoundError: No module named 'airflow.providers.github'
[2023-05-04T02:16:41.498+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:16:41.545+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/clone_repo.py took 0.087 seconds
[2023-05-04T02:16:42.470+0000] {processor.py:153} INFO - Started process (PID=776) to work on /opt/airflow/dags/clone_repo.py
[2023-05-04T02:16:42.471+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/clone_repo.py for tasks to queue
[2023-05-04T02:16:42.472+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:16:42.472+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:16:42.478+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:16:42.476+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/clone_repo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/clone_repo.py", line 2, in <module>
    from airflow.providers.github.operators.github import GithubOperator
ModuleNotFoundError: No module named 'airflow.providers.github'
[2023-05-04T02:16:42.478+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:16:42.510+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/clone_repo.py took 0.046 seconds
[2023-05-04T02:16:55.581+0000] {processor.py:153} INFO - Started process (PID=777) to work on /opt/airflow/dags/clone_repo.py
[2023-05-04T02:16:55.582+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/clone_repo.py for tasks to queue
[2023-05-04T02:16:55.583+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:16:55.583+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:16:55.587+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:16:55.586+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/clone_repo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/clone_repo.py", line 2, in <module>
    from airflow.providers.github.operators.github import GithubOperator
ModuleNotFoundError: No module named 'airflow.providers.github'
[2023-05-04T02:16:55.587+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:16:55.611+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/clone_repo.py took 0.034 seconds
[2023-05-04T02:16:58.254+0000] {processor.py:153} INFO - Started process (PID=782) to work on /opt/airflow/dags/clone_repo.py
[2023-05-04T02:16:58.255+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/clone_repo.py for tasks to queue
[2023-05-04T02:16:58.256+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:16:58.256+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:16:58.261+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:16:58.260+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/clone_repo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/clone_repo.py", line 2, in <module>
    from airflow.providers.github.operators.github import GithubOperator
ModuleNotFoundError: No module named 'airflow.providers.github'
[2023-05-04T02:16:58.261+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:16:58.288+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/clone_repo.py took 0.038 seconds
[2023-05-04T02:17:28.482+0000] {processor.py:153} INFO - Started process (PID=792) to work on /opt/airflow/dags/clone_repo.py
[2023-05-04T02:17:28.486+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/clone_repo.py for tasks to queue
[2023-05-04T02:17:28.491+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:17:28.490+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:17:28.511+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:17:28.505+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/clone_repo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/clone_repo.py", line 2, in <module>
    from airflow.providers.github.operators.github import GithubOperator
ModuleNotFoundError: No module named 'airflow.providers.github'
[2023-05-04T02:17:28.512+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:17:28.582+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/clone_repo.py took 0.121 seconds
[2023-05-04T02:17:59.440+0000] {processor.py:153} INFO - Started process (PID=814) to work on /opt/airflow/dags/clone_repo.py
[2023-05-04T02:17:59.444+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/clone_repo.py for tasks to queue
[2023-05-04T02:17:59.448+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:17:59.447+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:17:59.459+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:17:59.456+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/clone_repo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/clone_repo.py", line 2, in <module>
    from airflow.providers.github.operators.github import GithubOperator
ModuleNotFoundError: No module named 'airflow.providers.github'
[2023-05-04T02:17:59.460+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:17:59.492+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/clone_repo.py took 0.072 seconds
[2023-05-04T02:18:29.734+0000] {processor.py:153} INFO - Started process (PID=827) to work on /opt/airflow/dags/clone_repo.py
[2023-05-04T02:18:29.737+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/clone_repo.py for tasks to queue
[2023-05-04T02:18:29.738+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:18:29.738+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:18:29.741+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:18:29.740+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/clone_repo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/clone_repo.py", line 2, in <module>
    from airflow.providers.github.operators.github import GithubOperator
ModuleNotFoundError: No module named 'airflow.providers.github'
[2023-05-04T02:18:29.742+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:18:29.765+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/clone_repo.py took 0.036 seconds
[2023-05-04T02:18:41.885+0000] {processor.py:153} INFO - Started process (PID=835) to work on /opt/airflow/dags/clone_repo.py
[2023-05-04T02:18:41.888+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/clone_repo.py for tasks to queue
[2023-05-04T02:18:41.891+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:18:41.890+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:18:41.906+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:18:41.902+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/clone_repo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/clone_repo.py", line 2, in <module>
    from airflow.providers.github.operators.github import GithubOperator
ModuleNotFoundError: No module named 'airflow.providers.github'
[2023-05-04T02:18:41.907+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:18:41.973+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/clone_repo.py took 0.106 seconds
[2023-05-04T02:19:12.251+0000] {processor.py:153} INFO - Started process (PID=849) to work on /opt/airflow/dags/clone_repo.py
[2023-05-04T02:19:12.253+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/clone_repo.py for tasks to queue
[2023-05-04T02:19:12.253+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:19:12.253+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:19:12.256+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:19:12.255+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/clone_repo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/clone_repo.py", line 2, in <module>
    from airflow.providers.github.operators.github import GithubOperator
ModuleNotFoundError: No module named 'airflow.providers.github'
[2023-05-04T02:19:12.257+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:19:12.282+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/clone_repo.py took 0.036 seconds
[2023-05-04T02:19:42.555+0000] {processor.py:153} INFO - Started process (PID=863) to work on /opt/airflow/dags/clone_repo.py
[2023-05-04T02:19:42.557+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/clone_repo.py for tasks to queue
[2023-05-04T02:19:42.558+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:19:42.558+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:19:42.566+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:19:42.565+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/clone_repo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/clone_repo.py", line 2, in <module>
    from airflow.providers.github.operators.github import GithubOperator
ModuleNotFoundError: No module named 'airflow.providers.github'
[2023-05-04T02:19:42.567+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:19:42.609+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/clone_repo.py took 0.061 seconds
[2023-05-04T02:20:12.749+0000] {processor.py:153} INFO - Started process (PID=877) to work on /opt/airflow/dags/clone_repo.py
[2023-05-04T02:20:12.752+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/clone_repo.py for tasks to queue
[2023-05-04T02:20:12.753+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:20:12.753+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:20:12.760+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:20:12.758+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/clone_repo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/clone_repo.py", line 2, in <module>
    from airflow.providers.github.operators.github import GithubOperator
ModuleNotFoundError: No module named 'airflow.providers.github'
[2023-05-04T02:20:12.760+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:20:12.791+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/clone_repo.py took 0.057 seconds
[2023-05-04T02:20:42.915+0000] {processor.py:153} INFO - Started process (PID=891) to work on /opt/airflow/dags/clone_repo.py
[2023-05-04T02:20:42.917+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/clone_repo.py for tasks to queue
[2023-05-04T02:20:42.919+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:20:42.919+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:20:42.927+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:20:42.925+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/clone_repo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/clone_repo.py", line 2, in <module>
    from airflow.providers.github.operators.github import GithubOperator
ModuleNotFoundError: No module named 'airflow.providers.github'
[2023-05-04T02:20:42.928+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:20:42.967+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/clone_repo.py took 0.071 seconds
[2023-05-04T02:21:13.170+0000] {processor.py:153} INFO - Started process (PID=905) to work on /opt/airflow/dags/clone_repo.py
[2023-05-04T02:21:13.172+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/clone_repo.py for tasks to queue
[2023-05-04T02:21:13.174+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:21:13.173+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:21:13.179+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:21:13.178+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/clone_repo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/clone_repo.py", line 2, in <module>
    from airflow.providers.github.operators.github import GithubOperator
ModuleNotFoundError: No module named 'airflow.providers.github'
[2023-05-04T02:21:13.180+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:21:13.207+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/clone_repo.py took 0.047 seconds
[2023-05-04T02:21:43.555+0000] {processor.py:153} INFO - Started process (PID=919) to work on /opt/airflow/dags/clone_repo.py
[2023-05-04T02:21:43.559+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/clone_repo.py for tasks to queue
[2023-05-04T02:21:43.562+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:21:43.561+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:21:43.574+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:21:43.569+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/clone_repo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/clone_repo.py", line 2, in <module>
    from airflow.providers.github.operators.github import GithubOperator
ModuleNotFoundError: No module named 'airflow.providers.github'
[2023-05-04T02:21:43.576+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:21:43.618+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/clone_repo.py took 0.077 seconds
[2023-05-04T02:22:13.914+0000] {processor.py:153} INFO - Started process (PID=933) to work on /opt/airflow/dags/clone_repo.py
[2023-05-04T02:22:13.917+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/clone_repo.py for tasks to queue
[2023-05-04T02:22:13.919+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:22:13.919+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:22:13.927+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:22:13.925+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/clone_repo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/clone_repo.py", line 2, in <module>
    from airflow.providers.github.operators.github import GithubOperator
ModuleNotFoundError: No module named 'airflow.providers.github'
[2023-05-04T02:22:13.928+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:22:13.960+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/clone_repo.py took 0.062 seconds
[2023-05-04T02:22:44.248+0000] {processor.py:153} INFO - Started process (PID=947) to work on /opt/airflow/dags/clone_repo.py
[2023-05-04T02:22:44.248+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/clone_repo.py for tasks to queue
[2023-05-04T02:22:44.249+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:22:44.249+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:22:44.252+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:22:44.251+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/clone_repo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/clone_repo.py", line 2, in <module>
    from airflow.providers.github.operators.github import GithubOperator
ModuleNotFoundError: No module named 'airflow.providers.github'
[2023-05-04T02:22:44.253+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:22:44.280+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/clone_repo.py took 0.036 seconds
[2023-05-04T02:23:14.724+0000] {processor.py:153} INFO - Started process (PID=961) to work on /opt/airflow/dags/clone_repo.py
[2023-05-04T02:23:14.731+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/clone_repo.py for tasks to queue
[2023-05-04T02:23:14.735+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:23:14.734+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:23:14.744+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:23:14.742+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/clone_repo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/clone_repo.py", line 2, in <module>
    from airflow.providers.github.operators.github import GithubOperator
ModuleNotFoundError: No module named 'airflow.providers.github'
[2023-05-04T02:23:14.745+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:23:14.779+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/clone_repo.py took 0.081 seconds
[2023-05-04T02:23:45.116+0000] {processor.py:153} INFO - Started process (PID=975) to work on /opt/airflow/dags/clone_repo.py
[2023-05-04T02:23:45.118+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/clone_repo.py for tasks to queue
[2023-05-04T02:23:45.120+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:23:45.120+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:23:45.125+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:23:45.124+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/clone_repo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/clone_repo.py", line 2, in <module>
    from airflow.providers.github.operators.github import GithubOperator
ModuleNotFoundError: No module named 'airflow.providers.github'
[2023-05-04T02:23:45.126+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:23:45.163+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/clone_repo.py took 0.053 seconds
[2023-05-04T02:24:15.475+0000] {processor.py:153} INFO - Started process (PID=989) to work on /opt/airflow/dags/clone_repo.py
[2023-05-04T02:24:15.478+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/clone_repo.py for tasks to queue
[2023-05-04T02:24:15.481+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:24:15.480+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:24:15.490+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:24:15.487+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/clone_repo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/clone_repo.py", line 2, in <module>
    from airflow.providers.github.operators.github import GithubOperator
ModuleNotFoundError: No module named 'airflow.providers.github'
[2023-05-04T02:24:15.491+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:24:15.528+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/clone_repo.py took 0.064 seconds
[2023-05-04T02:24:45.846+0000] {processor.py:153} INFO - Started process (PID=1003) to work on /opt/airflow/dags/clone_repo.py
[2023-05-04T02:24:45.848+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/clone_repo.py for tasks to queue
[2023-05-04T02:24:45.850+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:24:45.849+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:24:45.857+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:24:45.855+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/clone_repo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/clone_repo.py", line 2, in <module>
    from airflow.providers.github.operators.github import GithubOperator
ModuleNotFoundError: No module named 'airflow.providers.github'
[2023-05-04T02:24:45.857+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:24:45.889+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/clone_repo.py took 0.058 seconds
[2023-05-04T02:25:16.250+0000] {processor.py:153} INFO - Started process (PID=1017) to work on /opt/airflow/dags/clone_repo.py
[2023-05-04T02:25:16.255+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/clone_repo.py for tasks to queue
[2023-05-04T02:25:16.258+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:25:16.258+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:25:16.272+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:25:16.268+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/clone_repo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/clone_repo.py", line 2, in <module>
    from airflow.providers.github.operators.github import GithubOperator
ModuleNotFoundError: No module named 'airflow.providers.github'
[2023-05-04T02:25:16.274+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:25:16.321+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/clone_repo.py took 0.096 seconds
[2023-05-04T02:25:46.679+0000] {processor.py:153} INFO - Started process (PID=1031) to work on /opt/airflow/dags/clone_repo.py
[2023-05-04T02:25:46.684+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/clone_repo.py for tasks to queue
[2023-05-04T02:25:46.687+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:25:46.687+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:25:46.703+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:25:46.700+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/clone_repo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/clone_repo.py", line 2, in <module>
    from airflow.providers.github.operators.github import GithubOperator
ModuleNotFoundError: No module named 'airflow.providers.github'
[2023-05-04T02:25:46.705+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:25:46.742+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/clone_repo.py took 0.081 seconds
[2023-05-04T02:26:17.085+0000] {processor.py:153} INFO - Started process (PID=1045) to work on /opt/airflow/dags/clone_repo.py
[2023-05-04T02:26:17.091+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/clone_repo.py for tasks to queue
[2023-05-04T02:26:17.095+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:26:17.094+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:26:17.105+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:26:17.103+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/clone_repo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/clone_repo.py", line 2, in <module>
    from airflow.providers.github.operators.github import GithubOperator
ModuleNotFoundError: No module named 'airflow.providers.github'
[2023-05-04T02:26:17.106+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:26:17.144+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/clone_repo.py took 0.084 seconds
[2023-05-04T02:26:47.528+0000] {processor.py:153} INFO - Started process (PID=1059) to work on /opt/airflow/dags/clone_repo.py
[2023-05-04T02:26:47.535+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/clone_repo.py for tasks to queue
[2023-05-04T02:26:47.540+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:26:47.539+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:26:47.558+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:26:47.553+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/clone_repo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/clone_repo.py", line 2, in <module>
    from airflow.providers.github.operators.github import GithubOperator
ModuleNotFoundError: No module named 'airflow.providers.github'
[2023-05-04T02:26:47.560+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:26:47.607+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/clone_repo.py took 0.105 seconds
[2023-05-04T02:27:17.701+0000] {processor.py:153} INFO - Started process (PID=1073) to work on /opt/airflow/dags/clone_repo.py
[2023-05-04T02:27:17.702+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/clone_repo.py for tasks to queue
[2023-05-04T02:27:17.703+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:27:17.703+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:27:17.708+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:27:17.707+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/clone_repo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/clone_repo.py", line 2, in <module>
    from airflow.providers.github.operators.github import GithubOperator
ModuleNotFoundError: No module named 'airflow.providers.github'
[2023-05-04T02:27:17.709+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:27:17.737+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/clone_repo.py took 0.042 seconds
[2023-05-04T02:27:47.851+0000] {processor.py:153} INFO - Started process (PID=1086) to work on /opt/airflow/dags/clone_repo.py
[2023-05-04T02:27:47.854+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/clone_repo.py for tasks to queue
[2023-05-04T02:27:47.855+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:27:47.855+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:27:47.860+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:27:47.859+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/clone_repo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/clone_repo.py", line 2, in <module>
    from airflow.providers.github.operators.github import GithubOperator
ModuleNotFoundError: No module named 'airflow.providers.github'
[2023-05-04T02:27:47.861+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:27:47.893+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/clone_repo.py took 0.048 seconds
[2023-05-04T02:28:18.015+0000] {processor.py:153} INFO - Started process (PID=1100) to work on /opt/airflow/dags/clone_repo.py
[2023-05-04T02:28:18.016+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/clone_repo.py for tasks to queue
[2023-05-04T02:28:18.016+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:28:18.016+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:28:18.019+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:28:18.018+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/clone_repo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/clone_repo.py", line 2, in <module>
    from airflow.providers.github.operators.github import GithubOperator
ModuleNotFoundError: No module named 'airflow.providers.github'
[2023-05-04T02:28:18.020+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:28:18.044+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/clone_repo.py took 0.033 seconds
[2023-05-04T02:28:46.887+0000] {processor.py:153} INFO - Started process (PID=1113) to work on /opt/airflow/dags/clone_repo.py
[2023-05-04T02:28:46.888+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/clone_repo.py for tasks to queue
[2023-05-04T02:28:46.889+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:28:46.889+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:28:46.894+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:28:46.892+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/clone_repo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/clone_repo.py", line 2, in <module>
    from airflow.providers.github.operators.github import GithubOperator
ModuleNotFoundError: No module named 'airflow.providers.github'
[2023-05-04T02:28:46.895+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:28:46.920+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/clone_repo.py took 0.037 seconds
[2023-05-04T02:29:17.838+0000] {processor.py:153} INFO - Started process (PID=1127) to work on /opt/airflow/dags/clone_repo.py
[2023-05-04T02:29:17.841+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/clone_repo.py for tasks to queue
[2023-05-04T02:29:17.842+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:29:17.842+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:29:17.846+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:29:17.845+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/clone_repo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/clone_repo.py", line 2, in <module>
    from airflow.providers.github.operators.github import GithubOperator
ModuleNotFoundError: No module named 'airflow.providers.github'
[2023-05-04T02:29:17.847+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:29:17.869+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/clone_repo.py took 0.041 seconds
[2023-05-04T02:29:47.988+0000] {processor.py:153} INFO - Started process (PID=1141) to work on /opt/airflow/dags/clone_repo.py
[2023-05-04T02:29:47.989+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/clone_repo.py for tasks to queue
[2023-05-04T02:29:47.990+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:29:47.989+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:29:47.993+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:29:47.992+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/clone_repo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/clone_repo.py", line 2, in <module>
    from airflow.providers.github.operators.github import GithubOperator
ModuleNotFoundError: No module named 'airflow.providers.github'
[2023-05-04T02:29:47.994+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:29:48.020+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/clone_repo.py took 0.036 seconds
[2023-05-04T02:30:18.273+0000] {processor.py:153} INFO - Started process (PID=1152) to work on /opt/airflow/dags/clone_repo.py
[2023-05-04T02:30:18.274+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/clone_repo.py for tasks to queue
[2023-05-04T02:30:18.276+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:30:18.275+0000] {dagbag.py:532} INFO - Filling up the DagBag from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:30:18.280+0000] {logging_mixin.py:137} INFO - [2023-05-04T02:30:18.279+0000] {dagbag.py:341} ERROR - Failed to import: /opt/airflow/dags/clone_repo.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 337, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/clone_repo.py", line 2, in <module>
    from airflow.providers.github.operators.github import GithubOperator
ModuleNotFoundError: No module named 'airflow.providers.github'
[2023-05-04T02:30:18.281+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/clone_repo.py
[2023-05-04T02:30:18.305+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/clone_repo.py took 0.041 seconds
